### ISSUE TITLE
Early science data is missing POSCIPA keyword

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdrp#105]
An example of this is exposure 3471.

In the current lvmdrp, ra's and dec's of the individual fibers are given in the SFrame data, so presumably either we are guessing that the PA is 0, or we have some other way of determining this.  If we know the PA then we should create and populate the keyword.  But even if is a guess, we should create the keyword (possibly with a warning in the header), and populate it with our best guess value, as this keyword is often used to make a WCS for the data in order to create images, and forcing every downstream program to account for this is time consuming.

**Comment by ndrory** [comment]
This needs to be fixed via HDRFIX.

**Comment by albireox** [comment]
I send this to a mailing list, but copying it here for completion

> If all these exposures have associated co-added guider frames those should be a pretty definitive answer. If that's not the case (and in that case I'm not sure if we could fully reduce those exposures) I think the sci guider frames would have recorded the position of the k-mirror, which would give a quite precise estimate of the PA.
>
> I can try to have a look at this in a few days, but if somebody wants to check, the lvm.sci.coadd_sXXXX.fits files have the PA in the first header. There is a PAFIELD keyword that if present shows the PA from the tile database; that one will probably be missing for early data. But there are two other keywords, PAMIN and PAMAX that are measured from the astrometry of the individual guider frames; the mean should be a good estimate of the PA (and of course you can also use the WCS).
>
> It may be good to do a few more automated filtering on that list. Looking at a few of the recent exposures in that list, some are actually arcs/flats, etc. A few simple tests that should remove object-but-not-science exposures:
>
> - Check if any of the lamps are on.
> - Check that the exposure time is not zero (and maybe at least 1-2 minutes).
> - Check that the exposure was taken between twilights.
