### ISSUE TITLE
There are no QA plots for the sky subtraction

### ISSUE THREAD

**Issue by ajmejia** [sdss/lvmdrp#106]

**Comment by kslong** [comment]
I have a quick evaluation routine which does produce such comparisons.  You can find it here

https://github.com/kslong/lvm_ksl

It's called QuickEval.py

**Comment by kslong** [comment]
There is an example of what the routine produces:

[LVMDRP Quality Asssessment for data_lvmSFrame-00005062.fits.pdf](https://github.com/user-attachments/files/15632304/LVMDRP.Quality.Asssessment.for.data_lvmSFrame-00005062.fits.pdf)

**Comment by ymamay** [comment]
adding skyQA plots via skyQA_dev branch.  Once merged then issue resolved
