### ISSUE TITLE
Standard star fibers are flux calibrated with average sensitivity curve, not the individual star’s curve

### ISSUE THREAD

**Issue by ndrory** [sdss/lvmdrp#107]
We see differences up to a factor of 2 when plotting the flux calibrated spectra of the observed standard stars against their GAIA XP spectra. That is because we are applying the average sensitivity curve to the standard star fibers. This is correct for the science and sky fibers that are exposed throughout the full observation, but it is incorrect for the standards that are exposed only for a short minute or so during the 15 min exposure. The standards should be calibrated with their individual sensitivity curve, and then their spectra will match GAIA as is expected.

**Comment by kslong** [comment]
Specifically, I find this plot very useful for understanding whether a frame had sky problems.  It compares the standards as they currently appear to the actual Gaia spectra of the same stars. The fact that they agree so well gives me confidence that there is no major issue  with the calibration:

<img width="1021" alt="image" src="https://github.com/sdss/lvmdrp/assets/2530901/b1cc830b-97ab-4ea0-a678-eb9c947c7e12">

**Comment by ajmejia** [comment]
For the sake of QA, let's do both. We can plot the standard stars calibrated with their own sensitivity curve and compare them with GaiaXP spectra. In the same plot we can also show the calibration of the standards with the mean sensitivity curve. This plot should be more informative than what we have now.

**Comment by kslong** [comment]
I agree that having both in a QA output would be useful; my comment was directed to what is actually contained in CFrame and SFrame FLUX extension, where I would prefer to see the stellar spectra calibrated with the "average" sensitivity for the exposure, modulo of course the actual exposure time.  

An alternative, or something additional that should be included in the header, is something that describes how consistent the sensitivity curves calculated from the various standard stars are.  This my not be straight forward of course, as there are a number of possible reasons one might not be consistent.   The one we want to know about is variable weather, but one can imagine that sometimes we don't get the standard star centered in the fiber, or there is something wrong with the GAIA spectrum.


(Assuming we think the instrument itself is stable of course, we should be able to identify bad weather by departures from the standard sensitivity.)

**Comment by ndrory** [comment]
This was fixed in 1.0.x
