### ISSUE TITLE
header keyword for re-observed tiles/dithers?

### ISSUE THREAD

**Issue by kreckel** [sdss/lvmdrp#118]
In looking through the data to analyze the geocoronal emission in the sky fields, I noticed that there is no easy way to find out if a given exposure was later marked as 'bad' and returned to the queue to be reobserved. For example, these LMC tiles I found have discrepant geocoronal line strenghts, and (all but one) were already reobserved.  They must have been marked as 'bad' at some point, though it is not obvious (to me) from the current header information what went wrong.  

#exposure MJD tile_id file
7693 60263 1028026 /data/LVM/sdsswork/lvm/spectro/redux/1.0.3/1028XX/1028026/60263/lvmSFrame-00007693.fits
7694 60263 1028026 /data/LVM/sdsswork/lvm/spectro/redux/1.0.3/1028XX/1028026/60263/lvmSFrame-00007694.fits
7695 60263 1028033 /data/LVM/sdsswork/lvm/spectro/redux/1.0.3/1028XX/1028033/60263/lvmSFrame-00007695.fits
7697 60263 1028033 /data/LVM/sdsswork/lvm/spectro/redux/1.0.3/1028XX/1028033/60263/lvmSFrame-00007697.fits
7699 60263 1028033 /data/LVM/sdsswork/lvm/spectro/redux/1.0.3/1028XX/1028033/60263/lvmSFrame-00007699.fits
7700 60263 1028033 /data/LVM/sdsswork/lvm/spectro/redux/1.0.3/1028XX/1028033/60263/lvmSFrame-00007700.fits
7701 60263 1028026 /data/LVM/sdsswork/lvm/spectro/redux/1.0.3/1028XX/1028026/60263/lvmSFrame-00007701.fits

Can we add a keyword to indicate if an exposure was marked to be reobserved? or (alternately) a keyword that the exposure is marked as bad? Or is this information that I should instead get from e.g. the drpall file? It seems more useful though if it is directly in the headers

**Comment by ndrory** [comment]
This is not a DRP issue, the DRP does not know about re-obervations. However, the QA pipeline and Dmitry should be setting a keyword via HDRFIX to indicate that an observation has been marked as bad by the QA pipeline.
