### ISSUE TITLE
Add every log warning emitted during reductions to header as COMMENT

### ISSUE THREAD

**Issue by ndrory** [sdss/lvmdrp#133]
Title says it all, add every log warning emitted during reductions to header as COMMENT so that we can filter by what happened. Additionally, we will add a keyword to the headers for each step in the reductions that at least reads 'SUCCESS', 'WARNING', 'FAIL'.

**Comment by kslong** [comment]
Outstanding

**Comment by havok2063** [comment]
I wouldn't recommend appending every log warning message into the headers.  This could result in the headers being hundreds of fields long, filled with log comments.  I would recommend using a single bitfield to capture which reduction steps a file has successfully made it through, maybe re-purposing these https://github.com/sdss/lvmdrp/blob/e275d938866f4ff1164dd8977bb8926b4360904e/python/lvmdrp/utils/bitmask.py#L142.  

Alternatively, the DRP reduction log files are output in JSON format as well as text format.  That makes the logs machine-readable and searchable.  One could write a simple tool or script that could parse and extract information from the json logs.  

In my opinion, the status and quality information should be captured with something like the following header keys, which would propagate into the drpall file.  This has the advantage of keeping the headers light and readable, but still tracking the details.  

- QUALITY - a bitfield tracking the output of Dmitry's QA
- DRPQUAL - a bitfield tracking errors and flags raised in the reductions
- REDUXSTATUS - a bitfield tracking which reduction stage of the pipeline was last successful
- STATUS - a single, final, string of reduction status, indicating "SUCCESS" or "FAIL" (possibly redundant)
- SCIENCEQUAL - a single, final, string quality of the overall quality, "GOOD" or "BAD" (possibly redundant)

**Comment by ndrory** [comment]
implemented in https://github.com/sdss/lvmdrp/pull/140
