### ISSUE TITLE
Issues with early science data reduction from newest DRP version 1.1.0.dev0

### ISSUE THREAD

**Issue by Amrita27singh** [sdss/lvmdrp#143]
Hi Alfredo,

I pulled the recent DRP version and lvmcore from git, I also downloaded all new master calibration frames from SAS to reduce Lagoon nebula data. I have been facing issues reducing the data on my Mac. 

Specifically, I tried reducing tiles from MJD = [60178, 60179, 60186] and exposure num= [3500-3505, 3595, 3991]. The drp fails after a while at the following step (attaching screenshot):

![image](https://github.com/user-attachments/assets/f5ec1648-4f84-4b85-a9a4-218d35c0b81c)
![image](https://github.com/user-attachments/assets/860da506-8c51-4ee6-bce3-268defb585ac)

Please let me know in case you require more information on above.
Thank you very much!

**Comment by EvelynJ** [comment]
Hi Amrita. I'm getting the same error message as your first image, also for early science data (MJD 60222, exp 6105). I've just downloaded the latest versions of LVMDRP, LVMCORE and the master calibrations, and have a fresh install of conda. I haven't yet found a solution

**Comment by Amrita27singh** [comment]
Hi Evelyn, 
Thanks for reporting the error, Oleg has seen similar issue in one of his tiles too. 

I talked to Alfredo this morning in the data call and he informed that they have already fixed the first error in a sub branch, which will probably be merged to main soon, and hopefully we'll be good to go then.
