### ISSUE TITLE
Latest DRP version failing for this data set

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdrp#151]
For me, the DRP is failing on this dataset for this commit  621aa190ddd7d1e0c84a7f9d20ddc71ac0ef4cde.  
The log is attached

[5013.log](https://github.com/user-attachments/files/17030016/5013.log)

I have processed this data set with 7e24b33 so something has cahnged

**Comment by ndrory** [comment]
Knox, we've looked into this one, and we can't reproduce a failure. This is an early exposure where we sometimes picked GAIA stars without BPRP spectra. The code correctly falls back on using stars in the science IFU, and the final frame is flux calibrated using that sensitivity curve. The exceptions you see are output as warnings to document the failure to obtain the BPRP spectra. There is no error that we can see. Perhaps we're misunderstanding what you're seeing?

**Comment by kslong** [comment]
Thanks.
