### ISSUE TITLE
Add heliocentric velocity correction

### ISSUE THREAD

**Issue by ndrory** [sdss/lvmdrp#156]
Either correct the lvmXFrames, or at least add a correction keyword to the header

**Comment by kslong** [comment]
I favor adding a keyword to the header, and not making corrections to the actual data in the DRP, as this will make assessing the quality of sky subtraction difficult.  The DAP should correct for this.

**Comment by ndrory** [comment]
Implemented in 1.1dev as 

HIERARCH WAVE HELIORV_SCI = -7.2169 / Heliocentric velocity correction for SCI [
HIERARCH WAVE HELIORV_SKYE = -7.9601 / Heliocentric velocity correction for SKYE
HIERARCH WAVE HELIORV_SKYW = -7.062 / Heliocentric velocity correction for SKYW
