### ISSUE TITLE
The header files produced by the DRP do not have keywords that contain the guider based astrometry

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdrp#175]
As I currently understand it, the headers of the CF and SF data do not contain the RA's, Dec's and PAs based on the guide star information, even though the fiber positions in the slit table to reflect this.  

We should either make clear that the header values Do Not reflect the improvements made to the guide start data, so that data cubes constructed from individual exposures are solely based on the values in the slit table, or we should add keywords to reflect this.

In particularly, the header values beginning with PO, which are the last positions in header, and might reasonble expected to be the final values are confusing, and do not reflect the actual position of a dithered exposure.

**Comment by ndrory** [comment]
Header keywords added in https://github.com/sdss/lvmdrp/commit/70d12f9ea32fe95af9566d1ad2ec89b04e61ec60
