### ISSUE TITLE
FWHM extension

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdrp#50]
Currently, in the lvmdrp (b52ad67ebe957dff406f41168c82f5fa55cffa8b) if one plots the FWHM exenension in the calibrated data for and exposure (in this case 7755), this is what one obtains.

<img width="731" alt="image" src="https://github.com/sdss/lvmdrp/assets/2530901/450105a9-a237-436c-95a8-efd1449a6dff">

Presumably the fact that one sees sharp jumps going to 0 in the minium FWHM is due to the fact that pixels marked as bad have given no FWHM.  But is this really what one wants.  I suggest filling these values in

**Comment by ajmejia** [comment]
Hi Knox, thanks for reporting this bug. In fact, the LSF or (FWHM as it is called in the files) is a polynomial model and shouldn't have masked pixels or what it seems to be absorption features. I'll track down this one to see where it its originating.

**Comment by ajmejia** [comment]
This issue was caused by a bad implementation of the method `apply_pixelmask` in the `RSS` class and a bug in the definition of the `weights` in the `from_channels` method of the same class.
