### ISSUE TITLE
Fiber Flat: Lack of good one!

### ISSUE THREAD

**Issue by sfsanchez72** [sdss/lvmdrp#58]
In the apply_fiberflat routine it is use a master fiberflat. It seems that the fiber-flat is an issue. I suggest we use an ad-hoc fiber-flat using the information from the sky emission lines.

**Comment by ndrory** [comment]
We've been planning on taking the master flat and arc, and shifting them to adjust them to each science frame using continuum and/or sky line information.

**Comment by ajmejia** [comment]
This was fixed in the PR #87. We still need to revisit the fiberflat fitting at the boundaries.
