### ISSUE TITLE
Better indication of successfull/failure in calibration is needed in the headers

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdrp#70]
As a specific example, currently there is no information to indicate whether the data was successfully flux calibrated. So, one can encounter a file where 5433, where apparently it was not possible to flux calibrate the data, but there is no indication of this in the primary header that this was the case.  Each step in the reduction should be accompanied by a keyword, saying whether that step had been successfully completed, and where appropriate giving some indication of what happened, e.g in the case of flux calibration, how many of the stars had spectra that were used in the flux calibration.

**Comment by ndrory** [comment]
FLUXCAL=CAL,SCI,NONE should indicate if and how the file was calibrated
