### ISSUE TITLE
add/clean headers of sky info

### ISSUE THREAD

**Issue by ymamay** [sdss/lvmdrp#82]
Add the header keyword for the FLI (fraction of lunar illumination) which is easier to interpret than alpha.  Can be added in skyMethod interpolate_sky with the other header keyword updates (only need one, no telescope dependence)

Could also clean up the header keywords to not repeat the sky model parameters that are agnostic to the the telescope (namely: sm_h, sm_hmin, alpha, altmoon, moondist, pres, ssa, calcds, o2column, moonscal, emis_str, temp_str, msolflux, season, time)

Adding the FLI is higher priority and should be simple fix

**Comment by havok2063** [comment]
Following https://github.com/sdss/lvmdrp/issues/77, I would like to make sure all new header keywords added have comments, describing that the keyword is.  @ymamay if you know what they are, can you provide a small description Alfredo could use, for each of the keywords you want added.

**Comment by ymamay** [comment]
Sure can do!  For this new one FLI the comment would be 'fraction of lunar illumination'. Could add 'where 1 is full and 0 is new moon' if you want more details.  I can add here (or maybe in 77) comments for the sky model parameters.
