### ISSUE TITLE
Flux calibration issue with [NII] 5755 A line

### ISSUE THREAD

**Issue by Amrita27singh** [sdss/lvmdrp#86]
![M8  NII 5755 Map](https://github.com/sdss/lvmdrp/assets/104734581/6c5a93db-ec7d-4703-bd4d-127570c7aa1c)

This is in reference to the Lagoon nebula data (observed as an early science target, MJDs 60178, 60179, 60186, 60188, 60191, 60203, 60228, 60231, 60232, 60236). [NII]5755 A line is on the edge of blue-red channel, and I am seeing inhomogeneous flux calibration in tiles, observed on different MJDs. Do you think it can be solved with updated DRP? Or we need to do manual adjustments? Please let me know in case you want me to run some tests.

Thanks!

**Comment by ajmejia** [comment]
@Amrita27singh reported this issue was solved in version 1.0.3. Here's the new map for comparison:

![NII 5755_new_drp](https://github.com/user-attachments/assets/9b9ba848-bd4d-48c2-ba25-85a9daabc885)
