### ISSUE TITLE
Wavelength sky shift sometimes shows a trend that is not corrected

### ISSUE THREAD

**Issue by ndrory** [sdss/lvmdrp#89]
![image](https://github.com/sdss/lvmdrp/assets/40801533/b1911587-fbad-48ae-ba05-0d2049693d77)

**Comment by ajmejia** [comment]
This trends are real and seem to be accentuated with MJD - calibrations epoch. The way we fixed this was by subtracting the fitted trend itself from the wavelength calibration. We also implemented sky lines centroid measurements using the same Gaussian fitting routine used in the wavelength/LSF fitting.

Here is the new version of the plot:

![lvmFrame-z-00014460_skylineshift_z](https://github.com/user-attachments/assets/4929369a-0f93-4c5d-ac06-1529915fbbd1)

As a sanity check, we re-run the sky lines matching routine on the corrected frame and this is the result:

![image](https://github.com/user-attachments/assets/a2ad9927-cce6-4b40-80b5-027b716b41e1)
