### ISSUE TITLE
Tracing is very slow

### ISSUE THREAD

**Issue by ndrory** [sdss/lvmdrp#92]
Investigate ways to make tracing faster. For example, fitting the profiles might be able to do with lower ftol and xtol values

**Comment by ajmejia** [comment]
As part of the improvements in the Gaussian fitting routines used in wavelength/LSF fitting (PR #129), we switched to `method='dogbox'` in `scipy.optimize.least_squares` (see commit 894a6dcf11aca5b7f363bd780aa5f742228ed407). This significantly speeds up tracing by a factor of >2: going from ~20-30min to ~10min per camera.

The consistency of the traces using one method or the other doesn't seem to be affected (TODO: verify this).

**Comment by ndrory** [comment]
as of sep 26, drp runtime is down to ~1200s at Utah. Extraction is ~10s and no longer dominant. The most computentially expensive step is now cosmic ray rejection.
