### ISSUE TITLE
Bad CCD columns not being blanked in output RSS files

### ISSUE THREAD

**Issue by tonywong94** [sdss/lvmdrp#95]
This shows an example, lvmSFrame-00004121.fits from MJD 60187, processed on 2024/05/24 using 1.0.2.dev0.  In the past, I believe we would set the black curved regions to NaN values.
![mjd60187_exp4121](https://github.com/sdss/lvmdrp/assets/4806117/251a9960-9974-40fb-bbb1-d92616f2e767)

**Comment by ndrory** [comment]
Fixed in 1.0.3
